package com.fordays.fdpay.cooperate._entity;



/**
 * ActionLog generated by hbm2java
 */


public class _ActionLog 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected java.sql.Timestamp logDate;
     protected Long logType;
     protected String content;
     protected Long status;
     protected com.fordays.fdpay.transaction.OrderDetails orderDetails;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public java.sql.Timestamp getLogDate() {
        return this.logDate;
    }
    
    public void setLogDate(java.sql.Timestamp logDate) {
        this.logDate = logDate;
    }
    


    public Long getLogType() {
        return this.logType;
    }
    
    public void setLogType(Long logType) {
        this.logType = logType;
    }
    


    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public com.fordays.fdpay.transaction.OrderDetails getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(com.fordays.fdpay.transaction.OrderDetails orderDetails) {
        this.orderDetails = orderDetails;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


