package com.fordays.fdpay.information._entity;



/**
 * News generated by hbm2java
 */


public class _News 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String title;
     protected String content;
     protected java.sql.Timestamp createDate;
     protected Long readNum;
     protected Long status;
     protected Long rank;
     protected String userName;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    


    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    


    public java.sql.Timestamp getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(java.sql.Timestamp createDate) {
        this.createDate = createDate;
    }
    


    public Long getReadNum() {
        return this.readNum;
    }
    
    public void setReadNum(Long readNum) {
        this.readNum = readNum;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public Long getRank() {
        return this.rank;
    }
    
    public void setRank(Long rank) {
        this.rank = rank;
    }
    


    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


