package com.fordays.fdpay.agent._entity;



/**
 * Account generated by hbm2java
 */


public class _Account 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String accountName;
     protected String cardName;
     protected String cardNo;
     protected Long cardType;
     protected java.sql.Timestamp createDate;
     protected java.sql.Timestamp frozenDate;
     protected Long certificationStatus;
     protected Long bindStatus;
     protected String accountAddress;
     protected Long bankId;
     protected com.fordays.fdpay.agent.Agent agent;
     protected com.fordays.fdpay.system.City city;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getAccountName() {
        return this.accountName;
    }
    
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }
    


    public String getCardName() {
        return this.cardName;
    }
    
    public void setCardName(String cardName) {
        this.cardName = cardName;
    }
    


    public String getCardNo() {
        return this.cardNo;
    }
    
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }
    


    public Long getCardType() {
        return this.cardType;
    }
    
    public void setCardType(Long cardType) {
        this.cardType = cardType;
    }
    


    public java.sql.Timestamp getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(java.sql.Timestamp createDate) {
        this.createDate = createDate;
    }
    


    public java.sql.Timestamp getFrozenDate() {
        return this.frozenDate;
    }
    
    public void setFrozenDate(java.sql.Timestamp frozenDate) {
        this.frozenDate = frozenDate;
    }
    


    public Long getCertificationStatus() {
        return this.certificationStatus;
    }
    
    public void setCertificationStatus(Long certificationStatus) {
        this.certificationStatus = certificationStatus;
    }
    


    public Long getBindStatus() {
        return this.bindStatus;
    }
    
    public void setBindStatus(Long bindStatus) {
        this.bindStatus = bindStatus;
    }
    


    public String getAccountAddress() {
        return this.accountAddress;
    }
    
    public void setAccountAddress(String accountAddress) {
        this.accountAddress = accountAddress;
    }
    


    public Long getBankId() {
        return this.bankId;
    }
    
    public void setBankId(Long bankId) {
        this.bankId = bankId;
    }
    


    public com.fordays.fdpay.agent.Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(com.fordays.fdpay.agent.Agent agent) {
        this.agent = agent;
    }
    


    public com.fordays.fdpay.system.City getCity() {
        return this.city;
    }
    
    public void setCity(com.fordays.fdpay.system.City city) {
        this.city = city;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


