package com.fordays.fdpay.agent._entity;



/**
 * AgentUserRoleRight generated by hbm2java
 */


public class _AgentUserRoleRight 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected com.fordays.fdpay.agent.AgentRoleRight agentRoleRight;
     protected com.fordays.fdpay.agent.AgentUser agentUser;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public com.fordays.fdpay.agent.AgentRoleRight getAgentRoleRight() {
        return this.agentRoleRight;
    }
    
    public void setAgentRoleRight(com.fordays.fdpay.agent.AgentRoleRight agentRoleRight) {
        this.agentRoleRight = agentRoleRight;
    }
    


    public com.fordays.fdpay.agent.AgentUser getAgentUser() {
        return this.agentUser;
    }
    
    public void setAgentUser(com.fordays.fdpay.agent.AgentUser agentUser) {
        this.agentUser = agentUser;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


