package com.fordays.fdpay.agent._entity;



/**
 * AgentBalancePoint generated by hbm2java
 */


public class _AgentBalancePoint 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String name;
     protected String email;
     protected Long agentId;
     protected java.math.BigDecimal allowBalance;
     protected java.math.BigDecimal notAllowBalance;
     protected java.sql.Timestamp balanceDate;
     protected java.math.BigDecimal creditBalance;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    


    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    


    public Long getAgentId() {
        return this.agentId;
    }
    
    public void setAgentId(Long agentId) {
        this.agentId = agentId;
    }
    


    public java.math.BigDecimal getAllowBalance() {
        return this.allowBalance;
    }
    
    public void setAllowBalance(java.math.BigDecimal allowBalance) {
        this.allowBalance = allowBalance;
    }
    


    public java.math.BigDecimal getNotAllowBalance() {
        return this.notAllowBalance;
    }
    
    public void setNotAllowBalance(java.math.BigDecimal notAllowBalance) {
        this.notAllowBalance = notAllowBalance;
    }
    


    public java.sql.Timestamp getBalanceDate() {
        return this.balanceDate;
    }
    
    public void setBalanceDate(java.sql.Timestamp balanceDate) {
        this.balanceDate = balanceDate;
    }
    


    public java.math.BigDecimal getCreditBalance() {
        return this.creditBalance;
    }
    
    public void setCreditBalance(java.math.BigDecimal creditBalance) {
        this.creditBalance = creditBalance;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


