package com.fordays.fdpay.agent._entity;



/**
 * Agent generated by hbm2java
 */


public class _Agent 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String name;
     protected String mobile;
     protected Long registerType;
     protected String address;
     protected String loginName;
     protected String password;
     protected String payPassword;
     protected String photo;
     protected Long status;
     protected String email;
     protected String tempEmail;
     protected String question2;
     protected String answer2;
     protected String question1;
     protected String answer1;
     protected String question;
     protected String answer;
     protected Long loginNum;
     protected String certification;
     protected String telephone;
     protected Long certType;
     protected String certNum;
     protected Long score;
     protected Long levelId;
     protected java.sql.Timestamp updateDate;
     protected java.sql.Timestamp registerDate;
     protected java.sql.Timestamp lastLoginDate;
     protected String loginIp;
     protected Long accountType;
     protected Long accountStatus;
     protected java.math.BigDecimal allowBalance;
     protected java.math.BigDecimal notallowBalance;
     protected java.math.BigDecimal creditBalance;
     protected java.math.BigDecimal consumeBalance;
     protected java.math.BigDecimal checkAmount;
     protected Long certStatus;
     protected Long mobileBindStatus;
     protected Long mobilePasswordStatus;
     protected Long mobileQuestionStatus;
     protected Long mobileLoginStatus;
     protected Long mobilePayStatus;
     protected java.math.BigDecimal maxItermAmount;
     protected java.math.BigDecimal maxDrawAmount;
     protected java.math.BigDecimal maxItemDrawAmount;
     protected java.math.BigDecimal maxDayAmount;
     protected Long canPay;
     protected String mobilePhone;
     protected java.sql.Timestamp currentLoginDate;
     protected Long rank;
     protected String companyName;
     protected java.util.Set sysLogs = new java.util.HashSet(0);
     protected java.util.Set taskTimestamps = new java.util.HashSet(0);
     protected java.util.Set draws = new java.util.HashSet(0);
     protected java.util.Set charges = new java.util.HashSet(0);
     protected java.util.Set chargeLogs = new java.util.HashSet(0);
     protected java.util.Set drawLogs = new java.util.HashSet(0);
     protected java.util.Set orderDetailss = new java.util.HashSet(0);
     protected java.util.Set debitLogs = new java.util.HashSet(0);
     protected java.util.Set debits = new java.util.HashSet(0);
     protected java.util.Set expenseLogs = new java.util.HashSet(0);
     protected java.util.Set expenses = new java.util.HashSet(0);
     protected java.util.Set accounts = new java.util.HashSet(0);
     protected java.util.Set agentAddresss = new java.util.HashSet(0);
     protected java.util.Set agentContacts = new java.util.HashSet(0);
     protected java.util.Set agentCoteries = new java.util.HashSet(0);
     protected java.util.Set coteries = new java.util.HashSet(0);
     protected java.util.Set agentRelationships = new java.util.HashSet(0);
     protected java.util.Set agentUsers = new java.util.HashSet(0);
     protected java.util.Set agentBalances = new java.util.HashSet(0);
     protected com.fordays.fdpay.agent.CertInfo certInfo;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    


    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    


    public Long getRegisterType() {
        return this.registerType;
    }
    
    public void setRegisterType(Long registerType) {
        this.registerType = registerType;
    }
    


    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    


    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }
    


    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    


    public String getPayPassword() {
        return this.payPassword;
    }
    
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword;
    }
    


    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    


    public String getTempEmail() {
        return this.tempEmail;
    }
    
    public void setTempEmail(String tempEmail) {
        this.tempEmail = tempEmail;
    }
    


    public String getQuestion2() {
        return this.question2;
    }
    
    public void setQuestion2(String question2) {
        this.question2 = question2;
    }
    


    public String getAnswer2() {
        return this.answer2;
    }
    
    public void setAnswer2(String answer2) {
        this.answer2 = answer2;
    }
    


    public String getQuestion1() {
        return this.question1;
    }
    
    public void setQuestion1(String question1) {
        this.question1 = question1;
    }
    


    public String getAnswer1() {
        return this.answer1;
    }
    
    public void setAnswer1(String answer1) {
        this.answer1 = answer1;
    }
    


    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    


    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    


    public Long getLoginNum() {
        return this.loginNum;
    }
    
    public void setLoginNum(Long loginNum) {
        this.loginNum = loginNum;
    }
    


    public String getCertification() {
        return this.certification;
    }
    
    public void setCertification(String certification) {
        this.certification = certification;
    }
    


    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    


    public Long getCertType() {
        return this.certType;
    }
    
    public void setCertType(Long certType) {
        this.certType = certType;
    }
    


    public String getCertNum() {
        return this.certNum;
    }
    
    public void setCertNum(String certNum) {
        this.certNum = certNum;
    }
    


    public Long getScore() {
        return this.score;
    }
    
    public void setScore(Long score) {
        this.score = score;
    }
    


    public Long getLevelId() {
        return this.levelId;
    }
    
    public void setLevelId(Long levelId) {
        this.levelId = levelId;
    }
    


    public java.sql.Timestamp getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(java.sql.Timestamp updateDate) {
        this.updateDate = updateDate;
    }
    


    public java.sql.Timestamp getRegisterDate() {
        return this.registerDate;
    }
    
    public void setRegisterDate(java.sql.Timestamp registerDate) {
        this.registerDate = registerDate;
    }
    


    public java.sql.Timestamp getLastLoginDate() {
        return this.lastLoginDate;
    }
    
    public void setLastLoginDate(java.sql.Timestamp lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }
    


    public String getLoginIp() {
        return this.loginIp;
    }
    
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }
    


    public Long getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(Long accountType) {
        this.accountType = accountType;
    }
    


    public Long getAccountStatus() {
        return this.accountStatus;
    }
    
    public void setAccountStatus(Long accountStatus) {
        this.accountStatus = accountStatus;
    }
    


    public java.math.BigDecimal getAllowBalance() {
        return this.allowBalance;
    }
    
    public void setAllowBalance(java.math.BigDecimal allowBalance) {
        this.allowBalance = allowBalance;
    }
    


    public java.math.BigDecimal getNotallowBalance() {
        return this.notallowBalance;
    }
    
    public void setNotallowBalance(java.math.BigDecimal notallowBalance) {
        this.notallowBalance = notallowBalance;
    }
    


    public java.math.BigDecimal getCreditBalance() {
        return this.creditBalance;
    }
    
    public void setCreditBalance(java.math.BigDecimal creditBalance) {
        this.creditBalance = creditBalance;
    }
    


    public java.math.BigDecimal getConsumeBalance() {
        return this.consumeBalance;
    }
    
    public void setConsumeBalance(java.math.BigDecimal consumeBalance) {
        this.consumeBalance = consumeBalance;
    }
    


    public java.math.BigDecimal getCheckAmount() {
        return this.checkAmount;
    }
    
    public void setCheckAmount(java.math.BigDecimal checkAmount) {
        this.checkAmount = checkAmount;
    }
    


    public Long getCertStatus() {
        return this.certStatus;
    }
    
    public void setCertStatus(Long certStatus) {
        this.certStatus = certStatus;
    }
    


    public Long getMobileBindStatus() {
        return this.mobileBindStatus;
    }
    
    public void setMobileBindStatus(Long mobileBindStatus) {
        this.mobileBindStatus = mobileBindStatus;
    }
    


    public Long getMobilePasswordStatus() {
        return this.mobilePasswordStatus;
    }
    
    public void setMobilePasswordStatus(Long mobilePasswordStatus) {
        this.mobilePasswordStatus = mobilePasswordStatus;
    }
    


    public Long getMobileQuestionStatus() {
        return this.mobileQuestionStatus;
    }
    
    public void setMobileQuestionStatus(Long mobileQuestionStatus) {
        this.mobileQuestionStatus = mobileQuestionStatus;
    }
    


    public Long getMobileLoginStatus() {
        return this.mobileLoginStatus;
    }
    
    public void setMobileLoginStatus(Long mobileLoginStatus) {
        this.mobileLoginStatus = mobileLoginStatus;
    }
    


    public Long getMobilePayStatus() {
        return this.mobilePayStatus;
    }
    
    public void setMobilePayStatus(Long mobilePayStatus) {
        this.mobilePayStatus = mobilePayStatus;
    }
    


    public java.math.BigDecimal getMaxItermAmount() {
        return this.maxItermAmount;
    }
    
    public void setMaxItermAmount(java.math.BigDecimal maxItermAmount) {
        this.maxItermAmount = maxItermAmount;
    }
    


    public java.math.BigDecimal getMaxDrawAmount() {
        return this.maxDrawAmount;
    }
    
    public void setMaxDrawAmount(java.math.BigDecimal maxDrawAmount) {
        this.maxDrawAmount = maxDrawAmount;
    }
    


    public java.math.BigDecimal getMaxItemDrawAmount() {
        return this.maxItemDrawAmount;
    }
    
    public void setMaxItemDrawAmount(java.math.BigDecimal maxItemDrawAmount) {
        this.maxItemDrawAmount = maxItemDrawAmount;
    }
    


    public java.math.BigDecimal getMaxDayAmount() {
        return this.maxDayAmount;
    }
    
    public void setMaxDayAmount(java.math.BigDecimal maxDayAmount) {
        this.maxDayAmount = maxDayAmount;
    }
    


    public Long getCanPay() {
        return this.canPay;
    }
    
    public void setCanPay(Long canPay) {
        this.canPay = canPay;
    }
    


    public String getMobilePhone() {
        return this.mobilePhone;
    }
    
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }
    


    public java.sql.Timestamp getCurrentLoginDate() {
        return this.currentLoginDate;
    }
    
    public void setCurrentLoginDate(java.sql.Timestamp currentLoginDate) {
        this.currentLoginDate = currentLoginDate;
    }
    


    public Long getRank() {
        return this.rank;
    }
    
    public void setRank(Long rank) {
        this.rank = rank;
    }
    


    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    


    public java.util.Set getSysLogs() {
        return this.sysLogs;
    }
    
    public void setSysLogs(java.util.Set sysLogs) {
        this.sysLogs = sysLogs;
    }
    


    public java.util.Set getTaskTimestamps() {
        return this.taskTimestamps;
    }
    
    public void setTaskTimestamps(java.util.Set taskTimestamps) {
        this.taskTimestamps = taskTimestamps;
    }
    


    public java.util.Set getDraws() {
        return this.draws;
    }
    
    public void setDraws(java.util.Set draws) {
        this.draws = draws;
    }
    


    public java.util.Set getCharges() {
        return this.charges;
    }
    
    public void setCharges(java.util.Set charges) {
        this.charges = charges;
    }
    


    public java.util.Set getChargeLogs() {
        return this.chargeLogs;
    }
    
    public void setChargeLogs(java.util.Set chargeLogs) {
        this.chargeLogs = chargeLogs;
    }
    


    public java.util.Set getDrawLogs() {
        return this.drawLogs;
    }
    
    public void setDrawLogs(java.util.Set drawLogs) {
        this.drawLogs = drawLogs;
    }
    


    public java.util.Set getOrderDetailss() {
        return this.orderDetailss;
    }
    
    public void setOrderDetailss(java.util.Set orderDetailss) {
        this.orderDetailss = orderDetailss;
    }
    


    public java.util.Set getDebitLogs() {
        return this.debitLogs;
    }
    
    public void setDebitLogs(java.util.Set debitLogs) {
        this.debitLogs = debitLogs;
    }
    


    public java.util.Set getDebits() {
        return this.debits;
    }
    
    public void setDebits(java.util.Set debits) {
        this.debits = debits;
    }
    


    public java.util.Set getExpenseLogs() {
        return this.expenseLogs;
    }
    
    public void setExpenseLogs(java.util.Set expenseLogs) {
        this.expenseLogs = expenseLogs;
    }
    


    public java.util.Set getExpenses() {
        return this.expenses;
    }
    
    public void setExpenses(java.util.Set expenses) {
        this.expenses = expenses;
    }
    


    public java.util.Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(java.util.Set accounts) {
        this.accounts = accounts;
    }
    


    public java.util.Set getAgentAddresss() {
        return this.agentAddresss;
    }
    
    public void setAgentAddresss(java.util.Set agentAddresss) {
        this.agentAddresss = agentAddresss;
    }
    


    public java.util.Set getAgentContacts() {
        return this.agentContacts;
    }
    
    public void setAgentContacts(java.util.Set agentContacts) {
        this.agentContacts = agentContacts;
    }
    


    public java.util.Set getAgentCoteries() {
        return this.agentCoteries;
    }
    
    public void setAgentCoteries(java.util.Set agentCoteries) {
        this.agentCoteries = agentCoteries;
    }
    


    public java.util.Set getCoteries() {
        return this.coteries;
    }
    
    public void setCoteries(java.util.Set coteries) {
        this.coteries = coteries;
    }
    


    public java.util.Set getAgentRelationships() {
        return this.agentRelationships;
    }
    
    public void setAgentRelationships(java.util.Set agentRelationships) {
        this.agentRelationships = agentRelationships;
    }
    


    public java.util.Set getAgentUsers() {
        return this.agentUsers;
    }
    
    public void setAgentUsers(java.util.Set agentUsers) {
        this.agentUsers = agentUsers;
    }
    


    public java.util.Set getAgentBalances() {
        return this.agentBalances;
    }
    
    public void setAgentBalances(java.util.Set agentBalances) {
        this.agentBalances = agentBalances;
    }
    


    public com.fordays.fdpay.agent.CertInfo getCertInfo() {
        return this.certInfo;
    }
    
    public void setCertInfo(com.fordays.fdpay.agent.CertInfo certInfo) {
        this.certInfo = certInfo;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


