package com.fordays.fdpay.agent._entity;



/**
 * AgentRelationship generated by hbm2java
 */


public class _AgentRelationship 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected Long parentAgentId;
     protected java.sql.Timestamp createDate;
     protected java.sql.Timestamp expireDate;
     protected com.fordays.fdpay.agent.Agent agent;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public Long getParentAgentId() {
        return this.parentAgentId;
    }
    
    public void setParentAgentId(Long parentAgentId) {
        this.parentAgentId = parentAgentId;
    }
    


    public java.sql.Timestamp getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(java.sql.Timestamp createDate) {
        this.createDate = createDate;
    }
    


    public java.sql.Timestamp getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(java.sql.Timestamp expireDate) {
        this.expireDate = expireDate;
    }
    


    public com.fordays.fdpay.agent.Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(com.fordays.fdpay.agent.Agent agent) {
        this.agent = agent;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


