package com.fordays.fdpay.agent._entity;



/**
 * AgentRole generated by hbm2java
 */


public class _AgentRole 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String roleKey;
     protected String roleName;
     protected String roleDescription;
     protected Long roleType;
     protected Long roleStatus;
     protected Long roleSystem;
     protected java.util.Set agentRoleRights = new java.util.HashSet(0);

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getRoleKey() {
        return this.roleKey;
    }
    
    public void setRoleKey(String roleKey) {
        this.roleKey = roleKey;
    }
    


    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    


    public String getRoleDescription() {
        return this.roleDescription;
    }
    
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }
    


    public Long getRoleType() {
        return this.roleType;
    }
    
    public void setRoleType(Long roleType) {
        this.roleType = roleType;
    }
    


    public Long getRoleStatus() {
        return this.roleStatus;
    }
    
    public void setRoleStatus(Long roleStatus) {
        this.roleStatus = roleStatus;
    }
    


    public Long getRoleSystem() {
        return this.roleSystem;
    }
    
    public void setRoleSystem(Long roleSystem) {
        this.roleSystem = roleSystem;
    }
    


    public java.util.Set getAgentRoleRights() {
        return this.agentRoleRights;
    }
    
    public void setAgentRoleRights(java.util.Set agentRoleRights) {
        this.agentRoleRights = agentRoleRights;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


