package com.fordays.fdpay.agent._entity;



/**
 * AgentCoterie generated by hbm2java
 */


public class _AgentCoterie 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected java.sql.Timestamp createDate;
     protected Long status;
     protected java.sql.Timestamp fromDate;
     protected java.sql.Timestamp expireDate;
     protected java.math.BigDecimal creditAmount;
     protected java.math.BigDecimal minAmount;
     protected Long transactionScope;
     protected Long repaymentType;
     protected Long leaveDays;
     protected com.fordays.fdpay.agent.Coterie coterie;
     protected com.fordays.fdpay.agent.Agent agent;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public java.sql.Timestamp getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(java.sql.Timestamp createDate) {
        this.createDate = createDate;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public java.sql.Timestamp getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(java.sql.Timestamp fromDate) {
        this.fromDate = fromDate;
    }
    


    public java.sql.Timestamp getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(java.sql.Timestamp expireDate) {
        this.expireDate = expireDate;
    }
    


    public java.math.BigDecimal getCreditAmount() {
        return this.creditAmount;
    }
    
    public void setCreditAmount(java.math.BigDecimal creditAmount) {
        this.creditAmount = creditAmount;
    }
    


    public java.math.BigDecimal getMinAmount() {
        return this.minAmount;
    }
    
    public void setMinAmount(java.math.BigDecimal minAmount) {
        this.minAmount = minAmount;
    }
    


    public Long getTransactionScope() {
        return this.transactionScope;
    }
    
    public void setTransactionScope(Long transactionScope) {
        this.transactionScope = transactionScope;
    }
    


    public Long getRepaymentType() {
        return this.repaymentType;
    }
    
    public void setRepaymentType(Long repaymentType) {
        this.repaymentType = repaymentType;
    }
    


    public Long getLeaveDays() {
        return this.leaveDays;
    }
    
    public void setLeaveDays(Long leaveDays) {
        this.leaveDays = leaveDays;
    }
    


    public com.fordays.fdpay.agent.Coterie getCoterie() {
        return this.coterie;
    }
    
    public void setCoterie(com.fordays.fdpay.agent.Coterie coterie) {
        this.coterie = coterie;
    }
    


    public com.fordays.fdpay.agent.Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(com.fordays.fdpay.agent.Agent agent) {
        this.agent = agent;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


