package com.fordays.fdpay.agent._entity;



/**
 * AgentBalance generated by hbm2java
 */


public class _AgentBalance 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String sessionId;
     protected Long userId;
     protected java.math.BigDecimal allowBalance;
     protected java.math.BigDecimal notAllowBalance;
     protected java.sql.Timestamp balanceDate;
     protected java.math.BigDecimal creditBalance;
     protected com.fordays.fdpay.agent.Agent agent;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
    


    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    


    public java.math.BigDecimal getAllowBalance() {
        return this.allowBalance;
    }
    
    public void setAllowBalance(java.math.BigDecimal allowBalance) {
        this.allowBalance = allowBalance;
    }
    


    public java.math.BigDecimal getNotAllowBalance() {
        return this.notAllowBalance;
    }
    
    public void setNotAllowBalance(java.math.BigDecimal notAllowBalance) {
        this.notAllowBalance = notAllowBalance;
    }
    


    public java.sql.Timestamp getBalanceDate() {
        return this.balanceDate;
    }
    
    public void setBalanceDate(java.sql.Timestamp balanceDate) {
        this.balanceDate = balanceDate;
    }
    


    public java.math.BigDecimal getCreditBalance() {
        return this.creditBalance;
    }
    
    public void setCreditBalance(java.math.BigDecimal creditBalance) {
        this.creditBalance = creditBalance;
    }
    


    public com.fordays.fdpay.agent.Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(com.fordays.fdpay.agent.Agent agent) {
        this.agent = agent;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


