package com.fordays.fdpay.agent._entity;



/**
 * AgentBind generated by hbm2java
 */


public class _AgentBind 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected Long agentId;
     protected Long bindAgentId;
     protected java.sql.Timestamp createDate;
     protected java.sql.Timestamp expireDate;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public Long getAgentId() {
        return this.agentId;
    }
    
    public void setAgentId(Long agentId) {
        this.agentId = agentId;
    }
    


    public Long getBindAgentId() {
        return this.bindAgentId;
    }
    
    public void setBindAgentId(Long bindAgentId) {
        this.bindAgentId = bindAgentId;
    }
    


    public java.sql.Timestamp getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(java.sql.Timestamp createDate) {
        this.createDate = createDate;
    }
    


    public java.sql.Timestamp getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(java.sql.Timestamp expireDate) {
        this.expireDate = expireDate;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


