package com.fordays.fdpay.agent._entity;



/**
 * CertInfo generated by hbm2java
 */


public class _CertInfo 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String serialNo;
     protected String userName;
     protected String certName;
     protected String ip;
     protected java.sql.Timestamp createDate;
     protected Long cardType;
     protected String cardNo;
     protected String mobil;
     protected String email;
     protected Long status;
     protected String password;
     protected java.util.Set agents = new java.util.HashSet(0);

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }
    


    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    


    public String getCertName() {
        return this.certName;
    }
    
    public void setCertName(String certName) {
        this.certName = certName;
    }
    


    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    


    public java.sql.Timestamp getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(java.sql.Timestamp createDate) {
        this.createDate = createDate;
    }
    


    public Long getCardType() {
        return this.cardType;
    }
    
    public void setCardType(Long cardType) {
        this.cardType = cardType;
    }
    


    public String getCardNo() {
        return this.cardNo;
    }
    
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }
    


    public String getMobil() {
        return this.mobil;
    }
    
    public void setMobil(String mobil) {
        this.mobil = mobil;
    }
    


    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    


    public java.util.Set getAgents() {
        return this.agents;
    }
    
    public void setAgents(java.util.Set agents) {
        this.agents = agents;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


