package com.fordays.fdpay.agent._entity;



/**
 * Coterie generated by hbm2java
 */


public class _Coterie 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String name;
     protected java.math.BigDecimal rate;
     protected String partner;
     protected String signKey;
     protected String signType;
     protected String allowMultcoterie;
     public String getAllowMultcoterie()
    {
    	return allowMultcoterie;
    }

		public void setAllowMultcoterie(String allowMultcoterie)
    {
    	this.allowMultcoterie = allowMultcoterie;
    }

		protected Long status;
     protected java.util.Set agentCoteries = new java.util.HashSet(0);
     protected com.fordays.fdpay.agent.Agent agent;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    


    public java.math.BigDecimal getRate() {
        return this.rate;
    }
    
    public void setRate(java.math.BigDecimal rate) {
        this.rate = rate;
    }
    


    public String getPartner() {
        return this.partner;
    }
    
    public void setPartner(String partner) {
        this.partner = partner;
    }
    


    public String getSignKey() {
        return this.signKey;
    }
    
    public void setSignKey(String signKey) {
        this.signKey = signKey;
    }
    


    public String getSignType() {
        return this.signType;
    }
    
    public void setSignType(String signType) {
        this.signType = signType;
    }
    


		public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public java.util.Set getAgentCoteries() {
        return this.agentCoteries;
    }
    
    public void setAgentCoteries(java.util.Set agentCoteries) {
        this.agentCoteries = agentCoteries;
    }
    


    public com.fordays.fdpay.agent.Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(com.fordays.fdpay.agent.Agent agent) {
        this.agent = agent;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


