package com.fordays.fdpay.transaction;

/**
 * Charge generated by hbm2java
 */

public class Statistic

extends org.apache.struts.action.ActionForm implements Cloneable
{
	private static final long serialVersionUID = 1L;

	private int index = 0;

	public int getIndex()
	{
		return index;
	}

	public void setIndex(int index)
	{
		this.index = index;
	}

	// end of extra code specified in the hbm.xml files

}
