package com.fordays.fdpay.transaction._entity;



/**
 * Charge generated by hbm2java
 */


public class _Charge 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String orderNo;
     protected String bank;
     protected String cardNo;
     protected java.math.BigDecimal amount;
     protected java.sql.Timestamp chargeDate;
     protected Long status;
     protected java.sql.Timestamp checkDate;
     protected Long user1Id;
     protected java.sql.Timestamp check1Date;
     protected String note;
     protected String type;
     protected String remark;
     protected String requestHost;
     protected com.fordays.fdpay.agent.Agent agent;
     protected com.fordays.fdpay.user.SysUser sysUser;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }
    


    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }
    


    public String getCardNo() {
        return this.cardNo;
    }
    
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }
    


    public java.math.BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(java.math.BigDecimal amount) {
        this.amount = amount;
    }
    


    public java.sql.Timestamp getChargeDate() {
        return this.chargeDate;
    }
    
    public void setChargeDate(java.sql.Timestamp chargeDate) {
        this.chargeDate = chargeDate;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public java.sql.Timestamp getCheckDate() {
        return this.checkDate;
    }
    
    public void setCheckDate(java.sql.Timestamp checkDate) {
        this.checkDate = checkDate;
    }
    


    public Long getUser1Id() {
        return this.user1Id;
    }
    
    public void setUser1Id(Long user1Id) {
        this.user1Id = user1Id;
    }
    


    public java.sql.Timestamp getCheck1Date() {
        return this.check1Date;
    }
    
    public void setCheck1Date(java.sql.Timestamp check1Date) {
        this.check1Date = check1Date;
    }
    


    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    


    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    


    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    


    public String getRequestHost() {
        return this.requestHost;
    }
    
    public void setRequestHost(String requestHost) {
        this.requestHost = requestHost;
    }
    


    public com.fordays.fdpay.agent.Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(com.fordays.fdpay.agent.Agent agent) {
        this.agent = agent;
    }
    


    public com.fordays.fdpay.user.SysUser getSysUser() {
        return this.sysUser;
    }
    
    public void setSysUser(com.fordays.fdpay.user.SysUser sysUser) {
        this.sysUser = sysUser;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


