package com.fordays.fdpay.transaction._entity;



/**
 * DrawLog generated by hbm2java
 */


public class _DrawLog 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String orderNo;
     protected java.math.BigDecimal amount;
     protected String content;
     protected java.sql.Timestamp chargeDate;
     protected Long status;
     protected com.fordays.fdpay.agent.Agent agent;
     protected com.fordays.fdpay.user.SysUser sysUser;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }
    


    public java.math.BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(java.math.BigDecimal amount) {
        this.amount = amount;
    }
    


    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    


    public java.sql.Timestamp getChargeDate() {
        return this.chargeDate;
    }
    
    public void setChargeDate(java.sql.Timestamp chargeDate) {
        this.chargeDate = chargeDate;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public com.fordays.fdpay.agent.Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(com.fordays.fdpay.agent.Agent agent) {
        this.agent = agent;
    }
    


    public com.fordays.fdpay.user.SysUser getSysUser() {
        return this.sysUser;
    }
    
    public void setSysUser(com.fordays.fdpay.user.SysUser sysUser) {
        this.sysUser = sysUser;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


