package com.fordays.fdpay.transaction._entity;



/**
 * Draw generated by hbm2java
 */


public class _Draw 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String orderNo;
     protected String bank;
     protected String cardNo;
     protected String accountBank;
     protected java.math.BigDecimal amount;
     protected java.sql.Timestamp drawDate;
     protected java.sql.Timestamp requestDate;
     protected Long status;
     protected java.sql.Timestamp checkDate;
     protected java.sql.Timestamp check1Date;
     protected String note;
     protected Long type;
     protected java.sql.Timestamp check3Date;
     protected com.fordays.fdpay.agent.Agent agent;
     protected com.fordays.fdpay.user.SysUser sysUser;
     protected com.fordays.fdpay.system.City city;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }
    


    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }
    


    public String getCardNo() {
        return this.cardNo;
    }
    
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }
    


    public String getAccountBank() {
        return this.accountBank;
    }
    
    public void setAccountBank(String accountBank) {
        this.accountBank = accountBank;
    }
    


    public java.math.BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(java.math.BigDecimal amount) {
        this.amount = amount;
    }
    


    public java.sql.Timestamp getDrawDate() {
        return this.drawDate;
    }
    
    public void setDrawDate(java.sql.Timestamp drawDate) {
        this.drawDate = drawDate;
    }
    


    public java.sql.Timestamp getRequestDate() {
        return this.requestDate;
    }
    
    public void setRequestDate(java.sql.Timestamp requestDate) {
        this.requestDate = requestDate;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public java.sql.Timestamp getCheckDate() {
        return this.checkDate;
    }
    
    public void setCheckDate(java.sql.Timestamp checkDate) {
        this.checkDate = checkDate;
    }
    




    public java.sql.Timestamp getCheck1Date() {
        return this.check1Date;
    }
    
    public void setCheck1Date(java.sql.Timestamp check1Date) {
        this.check1Date = check1Date;
    }
    


    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    


    public Long getType() {
        return this.type;
    }
    
    public void setType(Long type) {
        this.type = type;
    }
    



    public java.sql.Timestamp getCheck3Date() {
        return this.check3Date;
    }
    
    public void setCheck3Date(java.sql.Timestamp check3Date) {
        this.check3Date = check3Date;
    }
    


    public com.fordays.fdpay.agent.Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(com.fordays.fdpay.agent.Agent agent) {
        this.agent = agent;
    }
    


    public com.fordays.fdpay.user.SysUser getSysUser() {
        return this.sysUser;
    }
    
    public void setSysUser(com.fordays.fdpay.user.SysUser sysUser) {
        this.sysUser = sysUser;
    }
    


    public com.fordays.fdpay.system.City getCity() {
        return this.city;
    }
    
    public void setCity(com.fordays.fdpay.system.City city) {
        this.city = city;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


