package com.fordays.fdpay.transaction._entity;



/**
 * Expense generated by hbm2java
 */


public class _Expense 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String no;
     protected java.math.BigDecimal amount;
     protected java.sql.Timestamp applyDate;
     protected String userName;
     protected java.sql.Timestamp checkDate;
     protected String user1Name;
     protected java.sql.Timestamp check1Date;
     protected String user2Name;
     protected java.sql.Timestamp check2Date;
     protected String remark;
     protected String note;
     protected Long status;
     protected com.fordays.fdpay.transaction.Debit debit;
     protected com.fordays.fdpay.agent.Agent agent;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    




    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }
    


    public java.math.BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(java.math.BigDecimal amount) {
        this.amount = amount;
    }
    


    public java.sql.Timestamp getApplyDate() {
        return this.applyDate;
    }
    
    public void setApplyDate(java.sql.Timestamp applyDate) {
        this.applyDate = applyDate;
    }
    


    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    


    public java.sql.Timestamp getCheckDate() {
        return this.checkDate;
    }
    
    public void setCheckDate(java.sql.Timestamp checkDate) {
        this.checkDate = checkDate;
    }
    


    public String getUser1Name() {
        return this.user1Name;
    }
    
    public void setUser1Name(String user1Name) {
        this.user1Name = user1Name;
    }
    


    public java.sql.Timestamp getCheck1Date() {
        return this.check1Date;
    }
    
    public void setCheck1Date(java.sql.Timestamp check1Date) {
        this.check1Date = check1Date;
    }
    


    public String getUser2Name() {
        return this.user2Name;
    }
    
    public void setUser2Name(String user2Name) {
        this.user2Name = user2Name;
    }
    


    public java.sql.Timestamp getCheck2Date() {
        return this.check2Date;
    }
    
    public void setCheck2Date(java.sql.Timestamp check2Date) {
        this.check2Date = check2Date;
    }
    


    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    


    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public com.fordays.fdpay.transaction.Debit getDebit() {
        return this.debit;
    }
    
    public void setDebit(com.fordays.fdpay.transaction.Debit debit) {
        this.debit = debit;
    }
    


    public com.fordays.fdpay.agent.Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(com.fordays.fdpay.agent.Agent agent) {
        this.agent = agent;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


