package com.fordays.fdpay.transaction._entity;



/**
 * OrderDetails generated by hbm2java
 */


public class _OrderDetails 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String orderNo;
     protected String orderDetailsNo;
     protected String shopName;
     protected java.math.BigDecimal shopPrice;
     protected Long shopTotal;
     protected String shopUrl;
     protected String detailsContent;
     protected Long logisticsType;
     protected Long emailPriceUndertake;
     protected java.math.BigDecimal emailPrice;
     protected java.math.BigDecimal salePrice;
     protected Long orderDetailsType;
     protected Long buyType;
     protected String paymentReason;
     protected java.math.BigDecimal paymentPrice;
     protected String consigneeAddress;
     protected java.sql.Timestamp createDate;
     protected java.sql.Timestamp finishDate;
     protected Long status;
     protected String partner;
     protected String refundsNote;
     protected java.sql.Timestamp consignmentDate;
     protected java.sql.Timestamp repaymentDate;
     protected java.util.Set transactions = new java.util.HashSet(0);
     protected com.fordays.fdpay.agent.Agent agent;
     protected java.util.Set logisticss = new java.util.HashSet(0);
     protected java.util.Set actionLogs = new java.util.HashSet(0);

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }
    


    public String getOrderDetailsNo() {
        return this.orderDetailsNo;
    }
    
    public void setOrderDetailsNo(String orderDetailsNo) {
        this.orderDetailsNo = orderDetailsNo;
    }
    


    public String getShopName() {
        return this.shopName;
    }
    
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }
    


    public java.math.BigDecimal getShopPrice() {
        return this.shopPrice;
    }
    
    public void setShopPrice(java.math.BigDecimal shopPrice) {
        this.shopPrice = shopPrice;
    }
    


    public Long getShopTotal() {
        return this.shopTotal;
    }
    
    public void setShopTotal(Long shopTotal) {
        this.shopTotal = shopTotal;
    }
    


    public String getShopUrl() {
        return this.shopUrl;
    }
    
    public void setShopUrl(String shopUrl) {
        this.shopUrl = shopUrl;
    }
    


    public String getDetailsContent() {
        return this.detailsContent;
    }
    
    public void setDetailsContent(String detailsContent) {
        this.detailsContent = detailsContent;
    }
    


    public Long getLogisticsType() {
        return this.logisticsType;
    }
    
    public void setLogisticsType(Long logisticsType) {
        this.logisticsType = logisticsType;
    }
    


    public Long getEmailPriceUndertake() {
        return this.emailPriceUndertake;
    }
    
    public void setEmailPriceUndertake(Long emailPriceUndertake) {
        this.emailPriceUndertake = emailPriceUndertake;
    }
    


    public java.math.BigDecimal getEmailPrice() {
        return this.emailPrice;
    }
    
    public void setEmailPrice(java.math.BigDecimal emailPrice) {
        this.emailPrice = emailPrice;
    }
    


    public java.math.BigDecimal getSalePrice() {
        return this.salePrice;
    }
    
    public void setSalePrice(java.math.BigDecimal salePrice) {
        this.salePrice = salePrice;
    }
    


    public Long getOrderDetailsType() {
        return this.orderDetailsType;
    }
    
    public void setOrderDetailsType(Long orderDetailsType) {
        this.orderDetailsType = orderDetailsType;
    }
    


    public Long getBuyType() {
        return this.buyType;
    }
    
    public void setBuyType(Long buyType) {
        this.buyType = buyType;
    }
    


    public String getPaymentReason() {
        return this.paymentReason;
    }
    
    public void setPaymentReason(String paymentReason) {
        this.paymentReason = paymentReason;
    }
    


    public java.math.BigDecimal getPaymentPrice() {
        return this.paymentPrice;
    }
    
    public void setPaymentPrice(java.math.BigDecimal paymentPrice) {
        this.paymentPrice = paymentPrice;
    }
    


    public String getConsigneeAddress() {
        return this.consigneeAddress;
    }
    
    public void setConsigneeAddress(String consigneeAddress) {
        this.consigneeAddress = consigneeAddress;
    }
    


    public java.sql.Timestamp getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(java.sql.Timestamp createDate) {
        this.createDate = createDate;
    }
    


    public java.sql.Timestamp getFinishDate() {
        return this.finishDate;
    }
    
    public void setFinishDate(java.sql.Timestamp finishDate) {
        this.finishDate = finishDate;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public String getPartner() {
        return this.partner;
    }
    
    public void setPartner(String partner) {
        this.partner = partner;
    }
    


    public String getRefundsNote() {
        return this.refundsNote;
    }
    
    public void setRefundsNote(String refundsNote) {
        this.refundsNote = refundsNote;
    }
    


    public java.sql.Timestamp getConsignmentDate() {
        return this.consignmentDate;
    }
    
    public void setConsignmentDate(java.sql.Timestamp consignmentDate) {
        this.consignmentDate = consignmentDate;
    }
    


    public java.sql.Timestamp getRepaymentDate() {
        return this.repaymentDate;
    }
    
    public void setRepaymentDate(java.sql.Timestamp repaymentDate) {
        this.repaymentDate = repaymentDate;
    }
    


    public java.util.Set getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(java.util.Set transactions) {
        this.transactions = transactions;
    }
    


    public com.fordays.fdpay.agent.Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(com.fordays.fdpay.agent.Agent agent) {
        this.agent = agent;
    }
    


    public java.util.Set getLogisticss() {
        return this.logisticss;
    }
    
    public void setLogisticss(java.util.Set logisticss) {
        this.logisticss = logisticss;
    }
    


    public java.util.Set getActionLogs() {
        return this.actionLogs;
    }
    
    public void setActionLogs(java.util.Set actionLogs) {
        this.actionLogs = actionLogs;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


