package com.fordays.fdpay.transaction._entity;



/**
 * Transaction generated by hbm2java
 */


public class _Transaction 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected java.math.BigDecimal amount;
     protected Long action;
     protected Long type;
     protected java.sql.Timestamp accountDate;
     protected java.sql.Timestamp payDate;
     protected java.sql.Timestamp refundsDate;
     protected Long refundsStatus;
     protected String mark;
     protected Long flagStatus;
     protected java.sql.Timestamp closeDate;
     protected String closeReson;
     protected String no;
     protected Long status;
     protected java.math.BigDecimal currentBalance;
     protected com.fordays.fdpay.transaction.OrderDetails orderDetails;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public java.math.BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(java.math.BigDecimal amount) {
        this.amount = amount;
    }
    


    public Long getAction() {
        return this.action;
    }
    
    public void setAction(Long action) {
        this.action = action;
    }
    


    public Long getType() {
        return this.type;
    }
    
    public void setType(Long type) {
        this.type = type;
    }
    


    public java.sql.Timestamp getAccountDate() {
        return this.accountDate;
    }
    
    public void setAccountDate(java.sql.Timestamp accountDate) {
        this.accountDate = accountDate;
    }
    


    public java.sql.Timestamp getPayDate() {
        return this.payDate;
    }
    
    public void setPayDate(java.sql.Timestamp payDate) {
        this.payDate = payDate;
    }
    


    public java.sql.Timestamp getRefundsDate() {
        return this.refundsDate;
    }
    
    public void setRefundsDate(java.sql.Timestamp refundsDate) {
        this.refundsDate = refundsDate;
    }
    


    public Long getRefundsStatus() {
        return this.refundsStatus;
    }
    
    public void setRefundsStatus(Long refundsStatus) {
        this.refundsStatus = refundsStatus;
    }
    


    public String getMark() {
        return this.mark;
    }
    
    public void setMark(String mark) {
        this.mark = mark;
    }
    public Long getFlagStatus() {
      return this.flagStatus;
  }
  
  public void setFlagStatus(Long flagStatus) {
      this.flagStatus = flagStatus;
  }
    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public java.math.BigDecimal getCurrentBalance() {
        return this.currentBalance;
    }
    
    public void setCurrentBalance(java.math.BigDecimal currentBalance) {
        this.currentBalance = currentBalance;
    }
    


    public com.fordays.fdpay.transaction.OrderDetails getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(com.fordays.fdpay.transaction.OrderDetails orderDetails) {
        this.orderDetails = orderDetails;
    }


  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }

public java.sql.Timestamp getCloseDate()
{
	return closeDate;
}

public void setCloseDate(java.sql.Timestamp closeDate)
{
	this.closeDate = closeDate;
}

public String getCloseReson()
{
	return closeReson;
}

public void setCloseReson(String closeReson)
{
	this.closeReson = closeReson;
}
 





  // end of extra code specified in the hbm.xml files


}


