package com.fordays.fdpay.transaction._entity;



/**
 * TransactionBalance generated by hbm2java
 */


public class _TransactionBalance 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected Long transactionId;
     protected java.math.BigDecimal balance;
     protected java.math.BigDecimal creditBalance;
     protected Long agentId;
     protected Long status;
     protected java.sql.Timestamp transactionDate;
     protected java.math.BigDecimal notallowBalance;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public Long getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(Long transactionId) {
        this.transactionId = transactionId;
    }
    


    public java.math.BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(java.math.BigDecimal balance) {
        this.balance = balance;
    }
    


    public java.math.BigDecimal getCreditBalance() {
        return this.creditBalance;
    }
    
    public void setCreditBalance(java.math.BigDecimal creditBalance) {
        this.creditBalance = creditBalance;
    }
    


    public Long getAgentId() {
        return this.agentId;
    }
    
    public void setAgentId(Long agentId) {
        this.agentId = agentId;
    }
    


    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    


    public java.sql.Timestamp getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(java.sql.Timestamp transactionDate) {
        this.transactionDate = transactionDate;
    }
    


    public java.math.BigDecimal getNotallowBalance() {
        return this.notallowBalance;
    }
    
    public void setNotallowBalance(java.math.BigDecimal notallowBalance) {
        this.notallowBalance = notallowBalance;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


