package com.fordays.fdpay.system._entity;



/**
 * City generated by hbm2java
 */


public class _City 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String cname;
     protected String ename;
     protected com.fordays.fdpay.system.Province province;
     protected java.util.Set banks = new java.util.HashSet(0);
     protected java.util.Set draws = new java.util.HashSet(0);
     protected java.util.Set accounts = new java.util.HashSet(0);

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }
    


    public String getEname() {
        return this.ename;
    }
    
    public void setEname(String ename) {
        this.ename = ename;
    }
    


    public com.fordays.fdpay.system.Province getProvince() {
        return this.province;
    }
    
    public void setProvince(com.fordays.fdpay.system.Province province) {
        this.province = province;
    }
    


    public java.util.Set getBanks() {
        return this.banks;
    }
    
    public void setBanks(java.util.Set banks) {
        this.banks = banks;
    }
    


    public java.util.Set getDraws() {
        return this.draws;
    }
    
    public void setDraws(java.util.Set draws) {
        this.draws = draws;
    }
    


    public java.util.Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(java.util.Set accounts) {
        this.accounts = accounts;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


