package com.fordays.fdpay.system._entity;



/**
 * LogDetail generated by hbm2java
 */


public class _LogDetail 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected String refrenceCode;
     protected String content;
     protected com.fordays.fdpay.system.SysLog sysLog;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public String getRefrenceCode() {
        return this.refrenceCode;
    }
    
    public void setRefrenceCode(String refrenceCode) {
        this.refrenceCode = refrenceCode;
    }
    


    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    


    public com.fordays.fdpay.system.SysLog getSysLog() {
        return this.sysLog;
    }
    
    public void setSysLog(com.fordays.fdpay.system.SysLog sysLog) {
        this.sysLog = sysLog;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


