package com.fordays.fdpay.system._entity;



/**
 * SysLog generated by hbm2java
 */


public class _SysLog 

  extends org.apache.struts.action.ActionForm implements Cloneable
 {
	private static final long serialVersionUID = 1L;

    // Fields    

     protected long id;
     protected Long logType;
     protected java.sql.Timestamp logDate;
     protected String logContent;
     protected Long locate;
     protected java.util.Set logDetails = new java.util.HashSet(0);
     protected com.fordays.fdpay.user.SysUser sysUser;
     protected com.fordays.fdpay.agent.Agent agent;

     // Constructors
   
    // Property accessors


    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    


    public Long getLogType() {
        return this.logType;
    }
    
    public void setLogType(Long logType) {
        this.logType = logType;
    }
    


    public java.sql.Timestamp getLogDate() {
        return this.logDate;
    }
    
    public void setLogDate(java.sql.Timestamp logDate) {
        this.logDate = logDate;
    }
    


    public String getLogContent() {
        return this.logContent;
    }
    
    public void setLogContent(String logContent) {
        this.logContent = logContent;
    }
    


    public Long getLocate() {
        return this.locate;
    }
    
    public void setLocate(Long locate) {
        this.locate = locate;
    }
    


    public java.util.Set getLogDetails() {
        return this.logDetails;
    }
    
    public void setLogDetails(java.util.Set logDetails) {
        this.logDetails = logDetails;
    }
    


    public com.fordays.fdpay.user.SysUser getSysUser() {
        return this.sysUser;
    }
    
    public void setSysUser(com.fordays.fdpay.user.SysUser sysUser) {
        this.sysUser = sysUser;
    }
    


    public com.fordays.fdpay.agent.Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(com.fordays.fdpay.agent.Agent agent) {
        this.agent = agent;
    }
    




  // The following is extra code specified in the hbm.xml files

  public Object clone()
  {
    Object o = null;
    try
    {
      o = super.clone();
    }
    catch (CloneNotSupportedException e)
    {
      e.printStackTrace();
    }
    return o;
}

private String thisAction="";
 public String getThisAction()
 {
     return thisAction;
 }


public void setThisAction(String thisAction)
 {
     this.thisAction=thisAction;
 }

private int index=0;
 public int getIndex()
 {
     return index;
 }


public void setIndex(int index)
 {
     this.index=index;
 }
 





  // end of extra code specified in the hbm.xml files


}


